spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cramoss/configuration-properties.git

server:
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /manage

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://java-application-gae-1.rj.r.appspot.com/personal-eureka-server/eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF